# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
AdminUser.create!(email: 'shafquat_a@hotmail.com', password: 'password', password_confirmation: 'password')
AdminUser.create!(email: 'zaidtoorawa@gmail.com', password: 'password', password_confirmation: 'password')

Venue.create(name: 'Scotiabank Arena',address: '40 Bay St, Toronto, ON M5J 2X2', description: 'Scotiabank Arena, formerly Air Canada Centre, is a multi-purpose arena located on Bay Street in the South Core district of Downtown Toronto, Ontario, Canada.')
Venue.create(name: 'Rogers Centre',address: '1 Blue Jays Way, Toronto, ON M5V 1J1', description: 'Rogers Centre, originally named SkyDome, is a multi-purpose stadium in Downtown Toronto, Ontario, Canada, situated just southwest of the CN Tower near the northern shore of Lake Ontario. Opened in 1989 on the former Railway Lands, it is home to the Toronto Blue Jays of Major League Baseball.')
Venue.create(name: 'BMO Field',address: '170 Princes Blvd, Toronto, ON M6K 3C3', description: 'BMO Field is an outdoor stadium located at Exhibition Place in Toronto, Ontario, Canada, which is home to Toronto FC of Major League Soccer and the Toronto Argonauts of the Canadian Football League.')
Venue.create(name: 'Paramount Fine Foods Centre',address: '5500 Rose Cherry Pl, Mississauga, ON L4Z 4B6', description: 'The Paramount Fine Foods Centre, formerly the Hershey Centre, is a multi-purpose sports and entertainment complex located in Mississauga, Ontario, Canada. Its current name was adopted on July 1, 2018 following a new naming rights agreement with Mississauga-based restaurant chain Paramount Fine Foods.')
Venue.create(name: 'Coca-Cola Coliseum',address: '45 Manitoba Dr, Toronto, ON M6K 3C3', description: 'Coca-Cola Coliseum is an arena at Exhibition Place in Toronto, Ontario, Canada, used for agricultural displays, ice hockey and trade shows. It was built for the Canadian National Exhibition and the Royal Agricultural Winter Fair in 1921.')

Event.create(title: 'Toronto Raptors vs. Chicago Bulls (Preseason)', date: '2019-10-13 18:00:00', description: 'The Raptors only preseaon game in Toronto agains the Chicago Bulls', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. New Orleans Pelicans', date: '2019-10-22 20:00:00', description: 'Toronto Raptors vs. New Orleans Pelicans in the Home Opener', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Orlando Magic', date: '2019-10-28 19:30:00', description: 'Toronto Raptors vs. Orlando Magic', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Detroit Pistons', date: '2019-10-30 19:30:00', description: 'Toronto Raptors vs. Detroit Pistons', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Sacramento Kings', date: '2019-11-06 19:30:00', description: 'Toronto Raptors vs. Sacramento Kings', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Charlotte Hornets', date: '2019-11-18 19:30:00', description: 'Toronto Raptors vs. Charlotte Hornets', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Orlando Magic', date: '2019-11-20 19:30:00', description: 'Toronto Raptors vs. Orlando Magic', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Philadelphia 76ers', date: '2019-11-25 19:30:00', description: 'Toronto Raptors vs. Philadelphia 76ers', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. New York Knicks', date: '2019-11-27 19:30:00', description: 'Toronto Raptors vs. New York Knicks', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Utah Jazz', date: '2019-12-01 18:00:00', description: 'Toronto Raptors vs. Utah Jazz', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Miami Heat', date: '2019-12-03 19:30:00', description: 'Toronto Raptors vs. Miami Heat', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Houston Rockets', date: '2019-12-05 19:30:00', description: 'Toronto Raptors vs. Houston Rockets featuring Russell Westbrook and James Harden', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Los Angeles Clippers', date: '2019-12-11 19:30:00', description: 'Toronto Raptors vs. Los Angeles Clippers. The return of Kawhi Leonard', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Brooklyn Nets', date: '2019-12-14 19:30:00', description: 'Toronto Raptors vs. Brooklyn Nets', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Cleveland Cavaliers', date: '2019-12-16 19:30:00', description: 'Toronto Raptors vs. Cleveland Cavaliers', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Washington Wizards', date: '2019-12-20 19:30:00', description: 'Toronto Raptors vs. Washington Wizards', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Dallas Mavericks', date: '2019-12-22 15:30:00', description: 'Toronto Raptors vs. Dallas Mavericks', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Boston Celtics', date: '2019-12-25 12:00:00', description: 'Toronto Raptors vs. Boston Celtics in a Christmas Day match up', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Oklahoma City Thunder', date: '2019-12-29 18:00:00', description: 'Toronto Raptors vs. Oklahoma City Thunder', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Cleveland Cavaliers', date: '2019-12-31 19:00:00', description: 'Toronto Raptors vs. Cleveland Cavaliers', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Portland Trail Blazers', date: '2020-01-07 19:00:00', description: 'Toronto Raptors vs. Portland Trail Blazers', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. San Antonio Spurs', date: '2020-01-12 18:00:00', description: 'Toronto Raptors vs. San Antonio Spurs featuring fan favourite DeMar DeRozan', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Washington Wizards', date: '2020-01-17 19:00:00', description: 'Toronto Raptors vs. Washington Wizards', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Philadelphia 76ers', date: '2020-01-22 19:30:00', description: 'Toronto Raptors vs. Philadelphia 76ers', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Atlanta Hawks', date: '2020-01-28 19:30:00', description: 'Toronto Raptors vs. Atlanta Hawks', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Chicago Bulls', date: '2020-02-02 15:00:00', description: 'Toronto Raptors vs. Chicago Bulls', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Indiana Pacers', date: '2020-02-05 19:30:00', description: 'Toronto Raptors vs. Indiana Pacers', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Brooklyn Nets', date: '2020-02-08 19:30:00', description: 'Toronto Raptors vs. Brooklyn Nets', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Minnesota Timberwolves', date: '2020-02-10 19:30:00', description: 'Toronto Raptors vs. Minnesota Timberwolves', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Phoenix Suns', date: '2020-02-21 19:30:00', description: 'Toronto Raptors vs. Phoenix Suns', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Indiana Pacers', date: '2020-02-23 18:00:00', description: 'Toronto Raptors vs. Indiana Pacers', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Milwaukee Bucks', date: '2020-02-25 19:30:00', description: 'Toronto Raptors vs. Milwaukee Bucks featuring Giannis Antetokounmpo', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Charlotte Hornets', date: '2020-02-28 19:30:00', description: 'Toronto Raptors vs. Charlotte Hornets', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Detroit Pistons', date: '2020-03-14 19:30:00', description: 'Toronto Raptors vs. Detroit Pistons', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Golden State Warriors', date: '2020-03-16 20:00:00', description: 'Toronto Raptors vs. Golden State Warriors in a rematch of last years NBA Finals', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Boston Celtics', date: '2020-03-20 19:30:00', description: 'Toronto Raptors vs. Boston Celtics', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Denver Nuggets', date: '2020-03-22 18:00:00', description: 'Toronto Raptors vs. Denver Nuggets', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Los Angeles Lakers', date: '2020-03-24 19:30:00', description: 'Toronto Raptors vs. Los Angeles Lakers featuring LeBron James and Anthony Davis', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Memphis Grizzlies', date: '2020-03-30 19:30:00', description: 'Toronto Raptors vs. Memphis Grizzlies featuring fan favourite Jonas Valančiūnas', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Milwaukee Bucks', date: '2020-04-03 19:30:00', description: 'Toronto Raptors vs. Milwaukee Bucks featuring Giannis Antetokounmpo', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. Atlanta Hawks', date: '2020-04-10 19:30:00', description: 'Toronto Raptors vs. Atlanta Hawks', venue_id: 1)
Event.create(title: 'Toronto Raptors vs. New York Knicks', date: '2020-04-12 18:00:00', description: 'Toronto Raptors vs. New York Knicks', venue_id: 1)